# Generated by Django 5.2 on 2025-04-28 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Поставщик',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ФИО', models.CharField(max_length=255)),
                ('С_кем_можно_связаться', models.CharField(blank=True, max_length=255, null=True)),
                ('Должность', models.CharField(blank=True, max_length=100, null=True)),
                ('Адрес', models.TextField(blank=True, null=True)),
                ('Почтовой_индекс', models.CharField(blank=True, max_length=20, null=True)),
                ('Город', models.CharField(blank=True, max_length=100, null=True)),
                ('Страна', models.CharField(blank=True, max_length=100, null=True)),
                ('Телефон', models.CharField(max_length=20, unique=True)),
                ('Почта', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Сотрудник',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ФИО', models.CharField(max_length=255)),
                ('Должность', models.CharField(max_length=100)),
                ('Зарплата', models.DecimalField(decimal_places=2, max_digits=10)),
                ('День_найма', models.DateField()),
                ('Телефон', models.CharField(max_length=20, unique=True)),
                ('Почта', models.EmailField(max_length=100, unique=True)),
                ('Адрес', models.TextField(blank=True, null=True)),
                ('Дата_рождения', models.DateField(blank=True, null=True)),
                ('Отделение', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Покупатель',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ФИО', models.CharField(max_length=255)),
                ('Телефон', models.CharField(max_length=20, unique=True)),
                ('Почта', models.EmailField(max_length=100, unique=True)),
                ('Адрес', models.TextField(blank=True, null=True)),
                ('Дата_рождения', models.DateField(blank=True, null=True)),
                ('Пол', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10)),
                ('Дата_регистрации', models.DateTimeField(auto_now_add=True)),
                ('Бонусы', models.IntegerField(default=0)),
                ('Статус', models.CharField(choices=[('Активный', 'Активный'), ('Неактивный', 'Неактивный'), ('Заблокирован', 'Заблокирован')], default='Активный', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Продукт',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(max_length=255)),
                ('Категория', models.CharField(blank=True, max_length=100, null=True)),
                ('Цена', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Количество_на_складе', models.IntegerField(default=0)),
                ('Производитель', models.CharField(blank=True, max_length=255, null=True)),
                ('Срок_годности', models.DateField(blank=True, null=True)),
                ('Вес', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Описание_товара', models.TextField(blank=True, null=True)),
                ('Поставщик', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.поставщик')),
            ],
        ),
        migrations.CreateModel(
            name='Заказ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Дата_заказа', models.DateTimeField(auto_now_add=True)),
                ('Сумма_заказа', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Тип_статуса', models.CharField(choices=[('Обычный', 'Обычный'), ('VIP', 'VIP')], default='Обычный', max_length=50)),
                ('Статус_заказа', models.CharField(choices=[('В обработке', 'В обработке'), ('Отправлен', 'Отправлен'), ('Доставлен', 'Доставлен'), ('Отменен', 'Отменен')], default='В обработке', max_length=50)),
                ('Адрес_заказа', models.TextField()),
                ('Город_заказа', models.CharField(blank=True, max_length=100, null=True)),
                ('Область_заказа', models.CharField(blank=True, max_length=100, null=True)),
                ('Страна_заказа', models.CharField(blank=True, max_length=100, null=True)),
                ('Способ_оплаты', models.CharField(blank=True, max_length=50, null=True)),
                ('Айди_покупателя', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='заказы', to='shop.покупатель')),
                ('продукты', models.ManyToManyField(related_name='заказы', to='shop.продукт')),
            ],
        ),
        migrations.CreateModel(
            name='Расход',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Категория_расхода', models.CharField(blank=True, max_length=100, null=True)),
                ('Цена_расхода', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Когда_был_расход', models.DateTimeField(auto_now_add=True)),
                ('Способ_расхода', models.CharField(blank=True, max_length=50, null=True)),
                ('Номер_чека', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('Описание_расхода', models.TextField(blank=True, null=True)),
                ('Когда_написали_о_расходе', models.DateTimeField(auto_now_add=True)),
                ('Тип_расхода', models.CharField(blank=True, choices=[('Большой', '⚠️ Большой расход'), ('Обычный', '✅ Обычный расход')], max_length=50, null=True)),
                ('Кому_оплатил', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='Продажа',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название_продукта', models.CharField(max_length=255)),
                ('Количество', models.IntegerField(default=1)),
                ('Цена_за_продажу', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Дата', models.DateTimeField(auto_now_add=True)),
                ('Способ_оплаты', models.CharField(blank=True, max_length=50, null=True)),
                ('Айди_заказа', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.заказ')),
                ('Айди_продукта', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.продукт')),
                ('Айди_сотрудника', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='Платеж',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Когда_сделали_платеж', models.DateTimeField(auto_now_add=True)),
                ('Способ_платежа', models.CharField(max_length=50)),
                ('Сумма_платежа', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Номер_счет_фактурный', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('Описание_платежа', models.TextField(blank=True, null=True)),
                ('Статус_платежа', models.CharField(choices=[('Ожидание', 'Ожидание'), ('Оплачен', 'Оплачен'), ('Не оплачен', 'Не оплачен'), ('Ошибка', 'Ошибка')], default='Ожидание', max_length=50)),
                ('Когда_написали_о_платеже', models.DateTimeField(auto_now_add=True)),
                ('Кто_оплачивает', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.покупатель')),
                ('Кто_берет_оплату', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.сотрудник')),
            ],
        ),
    ]
