# Generated by Django 5.2 on 2025-04-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='покупатель',
            name='First_Name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='покупатель',
            name='Last_Name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
