# Generated by Django 5.2 on 2025-04-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_покупатель_first_name_покупатель_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='покупатель',
            name='user_type',
            field=models.CharField(choices=[('client', 'Покупатель'), ('admin', 'Администратор')], default='client', max_length=10),
        ),
    ]
